site_name: causaliq-pipeline
theme:
  name: material
  palette:
    # Light mode
    - scheme: light
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs  # so links appear in header
    - navigation.top   # adds a floating "to top" control



extra_css:
  - http://causaliq.org/css/mkdocs.css

nav:
  - Home: index.md
  - Requirements: 
    - Development Roadmap: roadmap.md
    - Example Workflows: example_workflows.md
  - Architecture: technical_architecture.md
  - Design Documents:
    - Matrix Strategy Design: design/matrix_expansion_design.md
    - Action Architecture: design/action_architecture_design.md
    - Algorithm Registry: design/algorithm_registry_design.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # setup_commands: Not needed anymore - paths option does same?
          #   - import sys; sys.path.insert(0, "src")
          paths: [src]
          options:
            show_source: false
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            relative_crossrefs: true
            scoped_crossrefs: true
            signature_crossrefs: true
            unwrap_annotated: true
            filters: public
            inherited_members: true
            summary: true
            heading_level: 2
            parameter_headings: true
            type_parameter_headings: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: false
            line_length: 88
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            backlinks: tree
            show_bases: false
            show_inheritance_diagram: true